### PR TITLE
fix: Closes #56

### LINKED ISSUE #56: Remove all mentions of my personal/shovel-org buckets
Any of my personal or shovel-org bucket should not be mentioned anywhere in this project

- `shovel-org/*`
- `Ash258/*`

### PR DESCRIPTION
**Pull request by Ash258**
- Closes #56

Original issue text:
```text
Remove all Ash258/* shovel-org/* buckets from this
```

Closing mysterious issue. 

I do not want to be listed as contributor. Implement it on your own and close this PR

### CODE REVIEW

**Comment by Ash258** [comment]
This repository breaks the GitHub community guidelines of misinformation and disinformation.
You are effectively mystifying scoop users that they can use my personal and shovel-org buckets, which is not true in most cases. And it could negatively influence their usage of scoop and I do not want to be connected with them. Like I do not care that your users will be confused about it, but you as a scoop developers, should be worried about this state.

Effectively this mystification will escalate even more with 1.1.2022 when all my buckets will be fully migrated.

I have no other option then report this repository, until this/similar change will be implemented. There were enough time to implement this.

**Comment by rashil2000** [comment]
> You are effectively mystifying scoop users that they can use my personal and shovel-org buckets, which is not true in most cases.

Actually, you're the one who's misleading Scoop users. If you want to get excluded from discovery by Scoop users, remove the tags 'scoop-bucket' and any substring 'scoop' from your repos. Otherwise Scoop people will keep having the misfortune of having to deal with you.

Once you remove these strings, scoop-directory's inclusion list will get updated automatically.

**Comment by Ash258** [comment]
No it will not be. My buckets are hardcoded

image

image

**Comment by rashil2000** [comment]
The list was generated programmatically at some point, because your repo contained the substring/tag as I mentioned. Remove the tags/strings/references, and your buckets will get removed once the list is regenerated at some point in the future.

**Pull request closed without merging**
